### PR TITLE
Update screenshot.rst

### PR DESCRIPTION
**Pull request by cseas**
Added description and example for 'confidence' keyword argument of pyautogui.locateOnScreen function.

### CODE REVIEW

**Comment by cseas** [comment]
Hi @asweigart 
Can you please take a look if this is correct?
I was using the locateOnScreen function and it took me a while to find there was a confidence parameter for it. So I updated the documentation.

**Comment by alphaCTzo7G** [comment]
+1 look good to me..

**Comment by medecau** [comment]
Hi,
Can anyone of you, @asweigart, @cseas, or @alphaCTzo7G(who added LGTM on this PR) please point to the commit where ```locateOnScreen``` takes the ```confidence``` parameter? 

The docs mention a confidence parameter but it is none existent in the code and looking back in git history it is nowhere to be found.

**Comment by cseas** [comment]
Hi @medecau 

As _Originally posted by @mogamepro in https://github.com/asweigart/pyautogui/issues/231#issuecomment-394072992_:
```No matter which pyautogui.locate function you call, you can pass the confidence parameter. They're all built off the .locateAll_opencv function and so it gets passed the confidence parameter through the kwargs.```

The `confidence` parameter was working fine at the time of this commit. However, it doesn't seem to be working anymore perhaps due to some change related to `.locateAll_opencv` mentioned above.

@asweigart @alphaCTzo7G Can you please look into what caused the `confidence` parameter to break?

**Comment by medecau** [comment]
I have done a bit of digging around this and the above is not entirely accurate.

The following is the definition of the function I expected to be using.
https://github.com/asweigart/pyautogui/blob/2744449d389a5cf4f6f54391faf903f832869198/pyautogui/screenshotUtil.py#L104

That definition is useless because of the following.
https://github.com/asweigart/pyautogui/blob/2744449d389a5cf4f6f54391faf903f832869198/pyautogui/__init__.py#L86

BTW, pyscreeze is not optional.
https://github.com/asweigart/pyautogui/blob/2744449d389a5cf4f6f54391faf903f832869198/setup.py#L26

But that's alright...

Then I expect the following to be the definition of the function I am using, which finally does match the docs and what is written above.
https://github.com/asweigart/pyscreeze/blob/d554797ce567e65697119c1f229a7de6dc6586c3/pyscreeze/__init__.py#L257

Which uses the function defined in:
https://github.com/asweigart/pyscreeze/blob/d554797ce567e65697119c1f229a7de6dc6586c3/pyscreeze/__init__.py#L247

Which then uses the mystery function defined after this revealing comment:
https://github.com/asweigart/pyscreeze/blob/d554797ce567e65697119c1f229a7de6dc6586c3/pyscreeze/__init__.py#L453

Which then points to one of the following:
https://github.com/asweigart/pyscreeze/blob/d554797ce567e65697119c1f229a7de6dc6586c3/pyscreeze/__init__.py#L106
https://github.com/asweigart/pyscreeze/blob/d554797ce567e65697119c1f229a7de6dc6586c3/pyscreeze/__init__.py#L157

In my case, and I assume that of a lot of other people that opened tickets regarding this missing parameter, it was the latter version that was being provided.

It seems then that pyautogui should require openvcv with a version number above 3 if it is to provide locate* functions with a confidence argument.

**Comment by medecau** [comment]
It seems adding `opencv-python>3` to this list will solve the problem:
https://github.com/asweigart/pyautogui/blob/2744449d389a5cf4f6f54391faf903f832869198/setup.py#L26

**Pull request merged**
